Created table for contacts
alkemyTech/OT287-server pull request #10
Opened 2022-09-15 19:25 UTC by MrLuis-WebMaster

## Jira Ticket

- [OT287-](https://alkemy-labs.atlassian.net/browse/OT287-72)

## Description
AS: Usuario administrador
I Want: Almacenar los datos al completar el formulario de Contacto
To: Tener una base de datos de Contactos

## Evidence:
![image](https://user-images.githubusercontent.com/75214315/190491567-a5a87609-f95d-469a-9334-f30662a7a90a.png)

2022-09-15 19:36 UTC, gabodmc approved these changes
Muy buen PR!

2022-09-15 20:06 UTC, federicocapucci approved these changes, later dismissed

2022-09-15 20:25 UTC, federicocapucci commented on database/models/contact.js
> +    deleteAt: DataTypes.DATE
@gabodmc  @MrLuis-WebMaster , no deberia ser borrado el deleteAt, como en el resto de modelos?

2022-09-15 20:32 UTC, gabodmc requested changes
Sumo unas correcciones

2022-09-15 20:32 UTC, gabodmc commented on database/migrations/20220915191302-create-contact.js
> +      deleteAt: {
deletedAt

2022-09-15 20:32 UTC, gabodmc commented on database/models/contact.js
> +    deleteAt: DataTypes.DATE
Tenes razon Fede, me sumo a esto. Este deleteAd no va

2022-09-15 20:33 UTC, guiniote requested changes

2022-09-15 20:33 UTC, guiniote commented on database/migrations/20220915191302-create-contact.js
> +      deleteAt: {
Ojo que es "deletedAt", no "deleteAt"

2022-09-15 20:33 UTC, guiniote commented on database/models/contact.js
> +    deleteAt: DataTypes.DATE
Como dijo Fede, acá habría que borrarlo.

2022-09-15 20:33 UTC, guiniote commented on database/models/contact.js
> +    modelName: 'Contact',
Acá tenés que agregar a continuación:
    paranoid: true,
    timestamps: true,

2022-09-16 02:23 UTC, MrLuis-WebMaster commented on database/models/contact.js
> +    deleteAt: DataTypes.DATE
ya subi el nuevo commit con los cambios

2022-09-16 02:29 UTC, guiniote requested changes
Fijate que sacaste el deletedAt del archivo de migrations, y solo tenías que sacarlo del archivo de model.

2022-09-16 02:29 UTC, guiniote commented on database/migrations/20220915191302-create-contact.js
> -      deleteAt: {
Esto no lo tenés que borrar, Luis. Solo le tenés que cambiar el nombre a "deletedAt"

2022-09-16 02:29 UTC, guiniote commented on database/migrations/20220915191302-create-contact.js
> +      createdAt: {
No tenías que borrar el "deletedAt" de acá, Luis

2022-09-16 03:08 UTC, guiniote approved these changes

2022-09-16 11:49 UTC, gabodmc approved these changes
Bien esas correcciones!

2022-09-16 12:21 UTC, eli-beg approved these changes

2022-09-16 19:36 UTC, merged