[SLIDES] ot287-31-create migration & model Slide
alkemyTech/OT287-server pull request #11
Opened 2022-09-15 20:37 UTC by GregoHouse

## Jira Ticket

- [OT287-](https://alkemy-labs.atlassian.net/jira/software/c/projects/OT287/boards/381?modal=detail&selectedIssue=OT287-31)

## Description
AS: administrator user
I Want: manage images
To: efficiently modify visual content

## Evidence:
waiting for OrganizatioId table to create slides table
![image](https://user-images.githubusercontent.com/96206226/190503665-9c54d28f-20fe-4fce-9afa-9e8bf6c0f8b9.png)

![image](https://user-images.githubusercontent.com/96206226/190503839-6bcb9aff-0087-4758-b68e-4a29d741e7b7.png)

2022-09-15 20:43 UTC, guiniote requested changes
Grego, fijate que hay un error de tipeo en la migración que va a bardear todo.

2022-09-15 20:43 UTC, guiniote commented on database/migrations/20220915195918-create-slide.js
> +      organiztionId: {
Error de tipeo! 😄

2022-09-15 22:17 UTC, GregoHouse commented on database/migrations/20220915195918-create-slide.js
> +      organiztionId: {
Como hiciste para ver eso Ger? Gracias nuevamente, se ve que por apurado borre sin querer.

2022-09-15 22:21 UTC, guiniote commented on database/migrations/20220915195918-create-slide.js
> +      organiztionId: {
Jajajaja, no sé, lo ví...me llamó la atención a la vista la z pegada a la t (?)

2022-09-15 22:23 UTC, GregoHouse commented on database/migrations/20220915195918-create-slide.js
> +      organiztionId: {
Sos un grande Ger!! gracias por ayudar.

2022-09-16 00:27 UTC, FrancoBaig requested changes

2022-09-16 00:27 UTC, FrancoBaig commented on database/models/slide.js
> +    organiztionId: DataTypes.INTEGER
tenés un error de tipeo acá, sería "organiz**a**tionId"

2022-09-16 00:27 UTC, FrancoBaig commented on database/models/slide.js
> +    text: DataTypes.STRING,
Conviene cambiar el DataType a "text"

2022-09-16 00:39 UTC, GregoHouse commented on database/models/slide.js
> +    organiztionId: DataTypes.INTEGER
El error de tipeo me lo marco Ger arriba. Ya esta resuelto, era solo en models.

2022-09-16 00:40 UTC, GregoHouse commented on database/models/slide.js
> +    text: DataTypes.STRING,
Fran, dale lo modifico

2022-09-16 00:42 UTC, GregoHouse commented on database/models/slide.js
> +      Slide.belongsTo(models.Role, {as: 'organizationId'});
Aca me acabo de dar cuenta que me olvide de borrar "Role" y poner "Organization". Lo habia cambiado para hacer la prueba y luego olvide modificarlo nuevamente.

2022-09-16 00:43 UTC, GregoHouse commented on database/models/slide.js
> +      Slide.belongsTo(models.Role, {as: 'organizationId'});
ahora subo commit nuevo con el cambio

2022-09-16 02:24 UTC, guiniote approved these changes

2022-09-16 02:36 UTC, federicocapucci approved these changes

2022-09-16 11:48 UTC, gabodmc requested changes
Lo veo todo muy bien, solo un pequeño cambio para algo que se fue del scope

2022-09-16 11:48 UTC, gabodmc commented on database/migrations/20220915195918-create-slide.js
> +        onDelete: 'SET NULL'
Las propiedades de de las lineas 26 y 27 no fueron solicitadas por la card.

2022-09-16 12:39 UTC, eli-beg commented on database/migrations/20220915195918-create-slide.js
> +      deletedAt: {
@gabodmc una consulta... este deletedAt no esta solicitado en la tarjeta

2022-09-16 12:41 UTC, FrancoBaig approved these changes

2022-09-16 13:38 UTC, gabodmc commented on database/migrations/20220915195918-create-slide.js
> +      deletedAt: {
Correcto. Habria que sacarlo

2022-09-16 14:30 UTC, GregoHouse commented on database/migrations/20220915195918-create-slide.js
> +        onDelete: 'SET NULL'
Gabo, listo resuelto.

2022-09-16 14:30 UTC, GregoHouse commented on database/migrations/20220915195918-create-slide.js
> +      deletedAt: {
Eli y Gabo, listo remove.

2022-09-16 14:39 UTC, guiniote approved these changes

2022-09-16 15:11 UTC, gabodmc approved these changes
Bien esas correcciones!

2022-09-16 15:13 UTC, merged