[Organization] OT287-18: Create endpoint for organization public data
alkemyTech/OT287-server pull request #12
Opened 2022-09-16 14:47 UTC by guiniote

## Jira Ticket

- [OT287-18](https://alkemy-labs.atlassian.net/browse/OT287-18)

## Description
AS: Desarrollador
I Want: Vincular Testimonios con API
To: Mostrar el contenido de forma dinámica

Criterios de aceptación: Petición GET hacia ruta /organizations/1/public
El endpoint deberá devolver un JSON con los campos name, image, phone, address y welcomeText

## Evidence:
![image](https://user-images.githubusercontent.com/79290983/190666704-ede76e42-ae87-445c-bd7f-d8e117fecf3b.png)

2022-09-16 15:32 UTC, gabodmc requested changes
El codigo esta muy bien, lo unico que tiene algunas redundancias en los nombres de los archivos.
Habria que dejarlo como organizations.js dentro de controllers, routes y services.

2022-09-16 22:31 UTC, gabodmc requested changes
Esta todo muy bien, solo un pequeño cambio

2022-09-16 22:31 UTC, gabodmc commented on app.js
> +app.use('/organizations', organizationsRouter)
mover esto al indexrouter

2022-09-18 13:54 UTC, gabodmc approved these changes
Buenas correcciones. Adentro este pr!

2022-09-18 16:06 UTC, FrancoBaig approved these changes
Perfecto Ger!

2022-09-18 17:55 UTC, ebereber approved these changes
un 10 ger.

2022-09-18 18:00 UTC, federicocapucci approved these changes
Excelente German 👏

2022-09-18 21:03 UTC, merged