Ot287 41 fix
alkemyTech/OT287-server pull request #16
Opened 2022-09-17 21:39 UTC by Gabitandil

## Jira Ticket

- [Ot287 41](https://alkemy-labs.atlassian.net/browse/OT287-41)

## Description
Renamed asociation name to fix error : "Error: Naming collision between attribute 'categoryId' and association 'categoryId' on model Entry. To remedy this, change either foreignKey or as in your association definition"

## Evidence:

![errror](https://user-images.githubusercontent.com/70545509/190877202-d4313835-bd01-43b6-9a62-02b9eb3eea59.png)

2022-09-17 21:50 UTC, guiniote requested changes
Fijate que te comenté algo, y la evidencia que pusiste es el error, no la solución 😛

2022-09-17 21:50 UTC, guiniote commented on database/models/entry.js
> +      Entry.belongsTo(models.Category, {as: "categories"} )
te diría que le pongas category a secas...así nos mantenemos en el singular.

2022-09-17 22:38 UTC, Gabitandil commented
> Fijate que te comenté algo, y la evidencia que pusiste es el error, no la solución stuck_out_tongue

estoy remarcando la linea que modifique asi cuando gabo lo vea ve que tenemos la linea 14 y la linea 22 con el mismo nombre, y de ahi el origen del error

2022-09-17 22:49 UTC, federicocapucci approved these changes

2022-09-17 23:12 UTC, guiniote approved these changes

2022-09-18 11:54 UTC, eli-beg approved these changes

2022-09-18 14:13 UTC, gabodmc approved these changes

2022-09-18 16:45 UTC, merged