[Users] OT287-33:  User Registration Endpoint
alkemyTech/OT287-server pull request #17
Opened 2022-09-17 23:15 UTC by federicocapucci

## Jira Ticket

- [OT287-](https://alkemy-labs.atlassian.net/browse/OT287-33)

## Description
AS: usuario
I Want: registrarme en el sistema
To: ser parte del mismo

Criterios de aceptación: POST /auth/register Deberá validar los campos Nombre, Apellido, Email, Contraseña. La contraseña debe ser encriptada. Deberá devolver como respuesta el usuario generado

Validar

Encriptar contraseña

Almacenar en base de datos

Para validar utilizaremos express validator https://express-validator.github.io/docs/

## Evidence:

Sccessful entry

![image](https://user-images.githubusercontent.com/547180/190879155-410b5b7d-1c0b-4a3b-adb7-b01cbadeee01.png)

Validation example

![image](https://user-images.githubusercontent.com/547180/190879229-14c1de55-713c-47c7-ac94-fe7dfd4d0f3e.png)

Validation example 2

![image](https://user-images.githubusercontent.com/547180/190879266-3bc7264a-9a68-4f0b-b155-53e6b070f73a.png)

2022-09-18 15:40 UTC, guiniote reviewed
Fede, te tiro un par de comentarios. Primero, lo que hiciste para validar no es un schema, hiciste un middleware 🤣
El schema sería extraer el "validateUser" de tu middleware en un archivo aparte, digamos. Y el middleware tiene que ser llamado como una función.
Otro tema, de nombres de archivo...esto tiene que estar controlado por el controller de usuarios...o sea, un users.js, con un router de usuarios...users.js...y el servicio también va en plural. 
Al margen, el create, que es lo que inserta en la base de datos también tiene que estar en el servicio, no en el controller.

2022-09-18 20:44 UTC, federicocapucci commented
> Fede, te tiro un par de comentarios. Primero, lo que hiciste para validar no es un schema, hiciste un middleware 🤣 El schema sería extraer el "validateUser" de tu middleware en un archivo aparte, digamos. Y el middleware tiene que ser llamado como una función. Otro tema, de nombres de archivo...esto tiene que estar controlado por el controller de usuarios...o sea, un users.js, con un router de usuarios...users.js...y el servicio también va en plural. Al margen, el create, que es lo que inserta en la base de datos también tiene que estar en el servicio, no en el controller.

Fixee lo siguiente:
- Nombres de archivos
- Mover codigo a los archivos correctos en router/services/schemas

Queda pendiente (y segun lo que pudimos hablar x discord) como meter el 'middleware'. de momento yse el schema directamente en el router.

2022-09-19 18:06 UTC, eli-beg reviewed
fijate que subiste los package.json, seguro fue en el utlimo update de la branch

2022-09-19 18:27 UTC, eli-beg commented on services/users.js
> +      const response = {
en este response mantendría el nombre de las propiedades en ingles

2022-09-19 18:27 UTC, eli-beg commented on controllers/users.js
> +// const { User } = require('../database/models')
te quedo este comentario para borrar

2022-09-20 00:16 UTC, GregoHouse requested changes

2022-09-20 00:16 UTC, GregoHouse commented on schemas/users.js
> +exports.users = {
Fede, creo que para seguir el mismo patrón de mensaje de errores estamos haciendo todo mensaje en lenguaje ingles. 

Por otro lado, sumo como recomendaciones las siguientes:
1) es muy importante el orden de las validaciones, ya que va ser el orden en que corren.
2) se puede usar tambien el metodo ".bail()" para que si no cumple esa validación no puede seguir con la otra y asi sucesivamente.
3) en password, hay una validación isStrongPassword que puede servirnos para darle mas seguridad.

2022-09-20 00:18 UTC, GregoHouse submitted a review, later dismissed

2022-09-20 00:18 UTC, GregoHouse commented on controllers/users.js
> +        message: 'Usuario creado',
Fede, idem. fijate que los mensajes estamos usando todos en ingles

2022-09-20 00:27 UTC, federicocapucci commented
> fijate que subiste los package.json, seguro fue en el utlimo update de la branch

explicado q es x el bcrypt

2022-09-20 01:42 UTC, federicocapucci commented on schemas/users.js
> +exports.users = {
listo

2022-09-20 01:47 UTC, Gabitandil approved these changes

2022-09-20 03:41 UTC, GregoHouse commented on controllers/users.js
> +const { createUser } = require('../services/users')
Fede, me da la sensación que aca en controller tenes que requerir todos los servicios para crear un USER:
1. servicio para saber si ya existe ese usuario registrado con ese email - usar servicio con findeOne
2. servicio para encryptar la contraseña

2022-09-20 03:41 UTC, GregoHouse commented on services/users.js
> +const encryptPassword = async (password) => {
Fede yo aca plantearia cada servicio con el patron forma de module.exports que venimos planteando

2022-09-20 03:41 UTC, GregoHouse commented on services/users.js
> +    const stringPassword = password.toString()
Fede, tampoco entiendo porque pasas el password a string? Entiendo que no haria falta. Podes pasar el req.password como viene para hashearlo.

2022-09-20 03:41 UTC, GregoHouse commented on services/users.js
> +module.exports = {
Fede porque no usas el mismo patron de codigo que se viene usando en services? Creo que estas usando el patrón de module exports que usamos en controller pero lo estas usando aca en services.
Deberias usar el:
export.nombre = async () => {
try
} catch {}

2022-09-20 03:41 UTC, GregoHouse commented on services/users.js
> +        firstName, lastName, email, password, image,
Fede, lo plantearia como:
1. data.firstname
2. data.lastName
3. data.email
4. data.password
5. data.image

2022-09-20 13:24 UTC, gabodmc requested changes
Esta todo muy bien. Solo un pequeño comentario

2022-09-20 13:24 UTC, gabodmc commented on services/users.js
> +      const encrypted = await encryptPassword(password)
Para la encriptación de contraseña no es necesario tener una funcion por fuera del servicio. Aca deberia hacer el hash directamente sobre el servicio

2022-09-20 16:08 UTC, federicocapucci commented on services/users.js
> +    const stringPassword = password.toString()
Porque me da un error de otra manera el bcrypt. La unica forma que pude solucionarlo es con ese codigo. Igual voy a probar a ver si lo puedo fixear de otra forma

2022-09-20 17:11 UTC, federicocapucci commented on services/users.js
> +        firstName, lastName, email, password, image,
ahi lo cambie para no utilizar variables intermedias innecesarias. gracias!

2022-09-20 17:12 UTC, federicocapucci commented on services/users.js
> +      const encrypted = await encryptPassword(password)
agregado adentro del servicio

2022-09-20 17:24 UTC, eli-beg approved these changes

2022-09-20 17:56 UTC, GregoHouse commented on services/users.js
> +      return null
Fede aca podes poner if (emailExists){
throw new ErrorObject('Email already exist', 404)
}

2022-09-20 17:56 UTC, GregoHouse commented on services/users.js
> +    const encryptedPassword = await bcrypt.hash(data.password.toString(), 10)
Fede sigo sin entender porque lo pasas a .toString() - Entiendo que no hace falta

2022-09-20 17:56 UTC, GregoHouse commented on services/users.js
> +    return response
Fede entiendo que tu return tiene que ser : return newUser para que se cree el usuario. Vos estas returnando el response.

2022-09-20 17:58 UTC, GregoHouse approved these changes

2022-09-20 18:07 UTC, gabodmc commented on services/users.js
> +    const encryptedPassword = await bcrypt.hash(data.password.toString(), 10)
Si, no es super necesario. No habria necesidad de sanitizarlo, ya que la validación la realizó el middleware

2022-09-20 18:08 UTC, gabodmc requested changes
Muy bienos cambios! Solo un pequeño detalle a corregir

2022-09-20 18:08 UTC, gabodmc commented on services/users.js
> +    return response
Me sumo tambien aca. El seteo del statuscode y demas es responsabilidad del controller

2022-09-20 18:17 UTC, federicocapucci commented on services/users.js
> +    return response
@GregoHouse  @gabodmc , saco el status code. Respecto a devolver el user. Necesito solamente devolver una parte del mismo, ya que no puedo retornar el password al front. dejo como esta? o mando un objeto sin nombre con ciertas keys de 'newUser'?

2022-09-20 18:47 UTC, federicocapucci commented on services/users.js
> +    const encryptedPassword = await bcrypt.hash(data.password.toString(), 10)
fixeado!

2022-09-20 18:48 UTC, federicocapucci commented on services/users.js
> +    return response
solucionado chateando x slack y discord

2022-09-20 20:58 UTC, gabodmc approved these changes
Bien esas correcciones!

2022-09-20 21:02 UTC, merged