[TESTIMONIAL] Enpoint for create testimonial
alkemyTech/OT287-server pull request #18
Opened 2022-09-17 23:35 UTC by MrLuis-WebMaster

## Jira Ticket

- [OT287-](https://alkemy-labs.atlassian.net/browse/OT287-85?atlOrigin=eyJpIjoiYTFkZmEwZjM3ZTc3NGRlM2E2MDliMzM2YTJiNTVkNmUiLCJwIjoiaiJ9)

## Description
AS: usuario administrador
I Want: dar de alta nuevos Testimonios
To:  informar Novedades acerca de la ONG.

## Evidence:

![image](https://user-images.githubusercontent.com/75214315/190879610-29b86f73-9c7a-4344-905a-c8272c5511ac.png)
![image](https://user-images.githubusercontent.com/75214315/190879641-b292310d-0bd6-4be9-85ab-83f805ad6ae2.png)

2022-09-18 14:13 UTC, gabodmc requested changes
Esta todo muy bien. Te deje un comentario y agrego algo por aca:
Dentro de la ruta y antes del metodo del controller, tiene que llamar a una funcion intermedia (middleware) que, segun el schema que le pasen, realize las validaciones correspondientes. 

Por otro lado, faltaria evidencia de que el middleware este funcionando y que errores devuelve

2022-09-18 14:13 UTC, gabodmc commented on routes/testimonials.js
> +    body('name').not().isEmpty(),
Esto deberia llamar a una funcion reutilizable con express-validator

2022-09-18 18:44 UTC, guiniote requested changes
Luis, en general está bien, pero fijate que hay algunas cosas a mejorar y otras pequeñas a corregir

2022-09-18 18:44 UTC, guiniote commented on routes/index.js
> +router.use('/testimonial', createTestimonial)
Luis, ojo que la tarjeta dice que tiene que postear a la ruta "testimonials", y lo pusiste en singular.

2022-09-18 18:44 UTC, guiniote commented on routes/testimonials.js
> +    body('name').not().isEmpty(),
Claro, como dijo en el comentario general Gabo, en lugar de poner el express validator en el medio del routeo, lo que tiene que estar ahí es un llamado a una función declarada en un archivo aparte (middleware) y que como parámetro se le pase el schema de validación que debe estar abstraido en otro archivo

2022-09-18 18:44 UTC, guiniote commented on services/testimonials.js
> +        if (!name || !content || !image) {
Esta validación deberías hacerla en el middleware, no acá en el servicio...y ojo que pide validar solo name y content (acá validás imagen también)

2022-09-18 23:29 UTC, MrLuis-WebMaster commented on routes/testimonials.js
> +    body('name').not().isEmpty(),
Equipo como van, esto me genera mucha confusión aun, sin embargo halle una manera que me parece reutilizable a traves de un schema

2022-09-18 23:32 UTC, MrLuis-WebMaster commented
Adjunto una evidencia de la repuesta de la peticion con los campos que son obligatorios

![image](https://user-images.githubusercontent.com/75214315/190932792-12244d92-eb76-411c-a172-5b1cc2b0936b.png)
![image](https://user-images.githubusercontent.com/75214315/190932815-db67b24d-c55a-4cd8-aae4-2851e8a1da28.png)

2022-09-18 23:51 UTC, GregoHouse requested changes

2022-09-18 23:51 UTC, GregoHouse commented on routes/testimonials.js
> +    validationTestimonialSchema(),
Luis, si lees bien el comentario de Gabo y Ger. Te estan diciendo si no me confundo, que aca vos tenes que:
1. poner el middleware
2. en ese mismo middleware que esta usando entre parentesis pone como parametro el shema.
pd: lo que estas haciendo vos estas poniendo como 2 middleware y no  1 middleware y pasar un paramentro adentro (el shema)

2022-09-19 00:02 UTC, MrLuis-WebMaster commented on routes/testimonials.js
> +    validationTestimonialSchema(),
Entiendo que el comentario el que recibe el parámetro seria el middleware, no se si estoy mal con eso, sin embargo hay algún ejemplo de el que pueda documentarme?

2022-09-19 00:07 UTC, GregoHouse commented on schemas/testimonials.js
> +        body('name').not().isEmpty().withMessage('name is required'),
capaz se puede refactorizar usando 1 metodo en vez de 2 metodos. Para que sea mas efectivo el codigo.
.notEmpty

2022-09-19 00:15 UTC, GregoHouse requested changes

2022-09-19 00:15 UTC, GregoHouse commented on controllers/testimonials.js
> +const { validationResult } = require('express-validator')
Luis, entiendo que no hace falta llamar aca el express validator. Se debe:
1. requerir y usar en el middleware
2. requerir el middleware en el archivo routes y usarlo como middleware pasando como parametro el shemas

2022-09-19 00:15 UTC, GregoHouse commented on controllers/testimonials.js
> +      // if (errors.length) {
Eliminar estos coments // ya q no hace falta usar el express validator y por ende el validationResults. Ya esta usandose en el archivo middleware

2022-09-19 00:41 UTC, GregoHouse requested changes

2022-09-19 00:41 UTC, GregoHouse commented on services/testimonials.js
> +exports.createTestimonial = async (name, content, image) => {
Capaz en vez de poner 3 req "(name, content, image)" como parametro de la función podrías poner 1 solo req como parametro "data". Y luego hacer el create con:
- data.name
- data.content
- data.image

2022-09-19 12:30 UTC, gabodmc requested changes
Esta muy bien el codigo en general. Solo unas pequeñas correcciones

2022-09-19 12:30 UTC, gabodmc commented on schemas/testimonials.js
> +const validationTestimonialSchema = () => {
Buscaria un nombre un poco mas corto, ejemplo: newTestimonial o solo testimonial, ya que tal vez uses el mismo esquema para crearlo o editarlo.

2022-09-19 12:30 UTC, gabodmc commented on middlewares/testimonials.js
> +const validationTestimonial = (req, res, next) => {
Esta perfecto el concepto, pero esto es una funcion reutilizable. Deberian tener una sola funcion para todas las validaciones. En esta parte van a tener que coordinar todos los que se encuentren haciendo validaciones en los endpoints

2022-09-19 12:30 UTC, gabodmc commented on services/testimonials.js
> +exports.createTestimonial = async (name, content, image) => {
+1

2022-09-19 18:57 UTC, eli-beg commented on routes/testimonials.js
> +    validationTestimonialSchema(),
el ejemplo que vimos el viernes era algo asi.
const { users } = require('schemas/users') // validacion del schema

router.post('/register', validationSchema(users), post)

ruta -- middleware -- controlador

2022-09-19 18:57 UTC, eli-beg commented on services/testimonials.js
> +        if (!testimonial) throw new ErrorObject('Error!', 400)
acá habría que detallar más el mensaje del error

2022-09-19 18:57 UTC, eli-beg commented on middlewares/testimonials.js
> +        `[Error retrieving Testimonial] - [Testimonial - POST]: ${name || content}`,
acá pondría creating Testimonial en lugar de retrieving Testimonial

2022-09-19 19:54 UTC, GregoHouse requested changes

2022-09-19 19:54 UTC, GregoHouse commented on routes/index.js
> +const createTestimonial = require('./testimonials')
creo que aca para seguir mismo patron nombres deberia ser testimonialsRouter

2022-09-20 02:27 UTC, MrLuis-WebMaster commented on routes/index.js
> +const createTestimonial = require('./testimonials')
Ya estaria el cambio hecho, quedo atento a cualquier solicitud

2022-09-20 02:28 UTC, MrLuis-WebMaster commented on middlewares/testimonials.js
> +        `[Error retrieving Testimonial] - [Testimonial - POST]: ${name || content}`,
Hola eli, ya estaria el cambio en este archivo, quedo atento a cualquier solicitud

2022-09-20 02:28 UTC, MrLuis-WebMaster commented on services/testimonials.js
> +        if (!testimonial) throw new ErrorObject('Error!', 400)
Ya se agrego mas descripcion al mensaje de error

2022-09-20 02:29 UTC, MrLuis-WebMaster commented on middlewares/testimonials.js
> +const validationTestimonial = (req, res, next) => {
ya estaria utilizando un middleware reutilizable

2022-09-20 02:31 UTC, MrLuis-WebMaster commented on services/testimonials.js
> +exports.createTestimonial = async (name, content, image) => {
Realize un cambio distinto me parecio un poco mas prolijo el codigo, sin embargo estoy atento para cambiarlo o si estan de acuerdo con el cambio

2022-09-20 02:32 UTC, MrLuis-WebMaster commented on routes/testimonials.js
> +    validationTestimonialSchema(),
Listo equipo ya esta utilizando un middleware reutilizable

2022-09-20 02:39 UTC, Gabitandil commented on routes/index.js
> +router.use('/news', entriesRouter)
fijate aca que creo que estas eliminando las rutas de la linea 14 15 y 16

2022-09-20 02:43 UTC, MrLuis-WebMaster commented on routes/index.js
> +router.use('/news', entriesRouter)
Uh se habra ido cuando me toco resolver conflictos

2022-09-20 02:48 UTC, Gabitandil approved these changes

2022-09-20 03:18 UTC, guiniote requested changes
Luis, está muy bien ahora el trabajo. Pero fijate que te dejé dos notas para aportar más legibilidad a tu código.

2022-09-20 03:18 UTC, guiniote commented on routes/testimonials.js
> +const { post } = require('../controllers/testimonials')
Luis, acá por una cuestión de claridad del código, en lugar de tener dos líneas enteras llamando al controller de testimonials, podrías tener const { post, destroy } = require('../controllers/testimonials') y así queda todo en una línea, más fácil de leer.

2022-09-20 03:18 UTC, guiniote commented on services/testimonials.js
> +        if (!testimonial) throw new ErrorObject('it was not possible to create testimonials', 400)
Este if está de más...con el try/catch para la creación alcanza. De hecho, y a partir de esto, tampoco hace falta que el await Testimonial.create lo asignes a una variable, ya que no tenés que hacer nada con eso y no devuelve nada el create...lo podés dejar solo y funciona OK igual, y aporta a la simplicidad del código.

2022-09-20 03:26 UTC, guiniote requested changes

2022-09-20 03:26 UTC, guiniote commented on controllers/testimonials.js
>  const { deleteById } = require('../services/testimonials')
Acá lo mismo que puse para el router, Luis

2022-09-20 13:10 UTC, eli-beg commented on controllers/testimonials.js
> +        body: response,
tal vez se puede sacar el response que devuelve el servicio, ya que no pide que devuelva el testimonio creado.  y agregar al msg Testimonial created succefully para seguir con el patron

2022-09-20 13:37 UTC, gabodmc requested changes
Esta todo super bien, solo un minimo cambio

2022-09-20 13:37 UTC, gabodmc commented on routes/testimonials.js
> +const { post } = require('../controllers/testimonials')
Me sumo a esto. Que raro que el lintern no te lo marcó como error.

2022-09-20 13:37 UTC, gabodmc commented on services/testimonials.js
> +        if (!testimonial) throw new ErrorObject('it was not possible to create testimonials', 400)
Concuerdo con lo del if. Teniendo el try catch ya basta, sobre todo porque en esta card no te piden ningun tipo de validacion sobre la respuesta de la db.
Lo que si dejaria es esa constante de testimonial y que el return devuelva el valor de la constante. Por temas de performance no tiene diferencia, y a veces son medio peligrosas las funciones autoejecutables.

2022-09-20 13:37 UTC, gabodmc commented on controllers/testimonials.js
> +        body: response,
Es común que se devuelva la respuesta de la db. Lo que les paso en algunas cards es que el cliente no quiere todos los datos, sino algunos puntuales

2022-09-20 18:47 UTC, guiniote approved these changes
Ahora sí!

2022-09-20 18:53 UTC, eli-beg approved these changes

2022-09-20 18:59 UTC, federicocapucci approved these changes

2022-09-20 20:02 UTC, ebereber approved these changes

2022-09-20 20:59 UTC, gabodmc approved these changes
Bien este pr. Aprobado!

2022-09-20 21:49 UTC, GregoHouse approved these changes

2022-09-20 21:55 UTC, merged