[ENTRY] Enpoint to create News
alkemyTech/OT287-server pull request #19
Opened 2022-09-18 17:47 UTC by Gabitandil

## Jira Ticket

- [OT287-](https://alkemy-labs.atlassian.net/browse/OT287-56)

## Description
AS: usuario administrador
I Want: crear una novedad 
To: mantener el contenido actualizado

Criterios de aceptación: POST /news - Deberá validar la existencia de los campos enviados, para almacenar el registro en la tabla entries. Antes de almacenarla, deberá asignarle la columna type con el valor "news".

## Evidence:
![evidencia1](https://user-images.githubusercontent.com/70545509/190921115-7998e0b5-ce16-4c21-83b7-c7f03ecd5891.png)
![evidencia2](https://user-images.githubusercontent.com/70545509/190921118-c75fc2c4-284d-42cb-9a08-e8593fb4c7ef.png)
![evidencia 2ymedio](https://user-images.githubusercontent.com/70545509/190921111-fca2f5be-7f4e-43e3-b462-19a969b727d1.png)

2022-09-18 18:28 UTC, federicocapucci reviewed
Hola Gabi, muy buen Pr. Deje un par de ocmments basado en lo que se estuvo hablando, algunas cosas capaz toca confirmarlas con el profe primero.

2022-09-18 18:28 UTC, federicocapucci commented on validators/entries.js
> +const { check } = require('express-validator')
@gabodmc  @Gabitandil @guiniote 
Corresponde crear una carpeta 'validators'? Lo he visto en algun video o proyecto, justo estabamos charlando con los compañeros donde y como meter la parte de validacion, y se hablo de schemas, llamados por un middleware. Como conviene?

2022-09-18 18:28 UTC, federicocapucci commented on controllers/news.js
> +  postEntry: catchAsync(async (req, res, next) => {
Segun lo que veniamos discutiendo, aca deberia ser 'createEntry' entiendo.

2022-09-18 18:28 UTC, federicocapucci commented on controllers/news.js
> +        `[Error retrieving index] - [index - GET]: ${error.message}`,
Este error se tiene que editar de acuerdo al endpoint

2022-09-18 18:32 UTC, Gabitandil commented on validators/entries.js
> +const { check } = require('express-validator')
tambien espero esa aclaracion, pero la cree porque me parece valido el cambio, pero segun lo que diga gabo lo modifico

2022-09-18 19:18 UTC, guiniote submitted a review, later dismissed
Gabi, hay varias cositas para ver, aunque varias quizás para charlar entre todos y con Gabo

2022-09-18 19:18 UTC, guiniote commented on validators/entries.js
> +const { check } = require('express-validator')
Esto es en verdad el middleware. Así que hay que meterlo en la carpeta middleware. Lo que yo creo es que no tiene sentido que tengamos 5 middleware de express-validator, ya que cada uno está haciendo el suyo en su branch. @gabodmc qué decís? nos deberíamos poner todos de acuerdo para que haya solo 1 middleware y que cada uno sí haga su schema?

Y tené en cuenta que en el middleware hay que exportar una función que reciba como parámetro un schema, y esta es llamada desde el router con el schema como parámetro.

2022-09-18 19:18 UTC, guiniote commented on validators/entries.js
> +const validateCreate = [
Esto es lo que sería el schema, todos los checks...que hay que meterlo en archivo aparte en la carpeta schemas

2022-09-18 19:18 UTC, guiniote commented on helpers/validateEntryHelper.js
> +const { validationResult } = require('express-validator')
Mmm...no estoy seguro de que este archivo sea necesario...

2022-09-18 19:18 UTC, guiniote commented on controllers/news.js
> +const createHttpError = require('http-errors')
El controller no es entries?

2022-09-18 21:06 UTC, GregoHouse requested changes

2022-09-18 21:06 UTC, GregoHouse commented on services/entries.js
>        throw new ErrorObject('No news found', 404)
No esta faltando aca el --> if (!createNew)???

2022-09-18 21:50 UTC, Gabitandil commented on services/entries.js
>        throw new ErrorObject('No news found', 404)
no porque esta el catch que devuelve el error si hay algo mal y esta el express validator puesto en la ruta .post en routes/entries linea 8 validando que los campos esten completos, si no lo estan, manda el error express validator y no se hace el create

2022-09-19 00:43 UTC, GregoHouse requested changes

2022-09-19 00:43 UTC, GregoHouse commented on helpers/validateEntryHelper.js
> +const { validationResult } = require('express-validator')
Pienso igual, dejaría los helpers con los que ya esta el proyecto.

2022-09-19 00:43 UTC, GregoHouse commented on routes/entries.js
> +const { validateCreate } = require('../validators/entries')
Entiendo que deberias requerir un middleware de la carpeta middlewares.
1. ir carpeta middlewares
2. crear entries.js 
3. requerirla en este archivo para usar el middleware
4. ir carpeta schema
5. crear el schema con las validaciones body metodos de express validator
6. requerir el schema en este archivo 
7. pasarle el schema como parametro al middleware

2022-09-19 00:53 UTC, GregoHouse requested changes, later dismissed

2022-09-19 00:53 UTC, GregoHouse commented on services/entries.js
>        throw new ErrorObject('No news found', 404)
para mi cada "try" tiene su "catch" y a su vez su if con negacion "!" - dejo mi comentario para tratarlos entre todos.

2022-09-19 01:37 UTC, Gabitandil commented on services/entries.js
>        throw new ErrorObject('No news found', 404)
dale mañana lo revisamos yo nunca me lo plantie asi que me gustaria saber cual es la practica optima

2022-09-19 01:44 UTC, Gabitandil commented on helpers/validateEntryHelper.js
> +const { validationResult } = require('express-validator')
yo considero que creando este helper le da mas prolijidad al schema, ademas de que mejora la escabilidad porque es reutilizable y se podria ampliar en el caso de que se requirieran mas funciones de express validator, pero estoy abierto a correcciones

2022-09-19 13:03 UTC, gabodmc requested changes
Esta encaminado, pero son necesarias algunas correcciones

2022-09-19 13:03 UTC, gabodmc commented on controllers/entries.js
> +  createEntry: catchAsync(async (req, res, next) => {
post:

2022-09-19 13:03 UTC, gabodmc commented on controllers/entries.js
> +        `[Error saving entry] - [entry - POST]: ${error.message}`,
Error creating entry

2022-09-19 13:03 UTC, gabodmc commented on helpers/validateEntryHelper.js
> +module.exports = { validateEntry }
Este archivo deberia ser un middleware, no un helper. Coordinar en equipo como van a plantear la funcion de validación y subir solo una

2022-09-19 13:03 UTC, gabodmc commented on validators/entries.js
> +module.exports = { validateCreate }
Esto iria en schemas. Y se lo debe pasar al middleware de validacion

2022-09-19 14:01 UTC, gabodmc requested changes
Va mejorando con las correcciones, pero todavia quedan unas cositas

2022-09-19 14:01 UTC, gabodmc commented on middlewares/validateEntry.js
> +const validateEntry = (req, res, next) => {
Esta tiene que ser una funcion reutilizable, que debe recibir el schema desde el route.

2022-09-19 14:01 UTC, gabodmc commented on controllers/entries.js
> +        `[Error creating entry] - [entry - POST]: ${error.message}`,
Aca esta bien la correccion. Por lo que estuve viendo, a entry la estan llamando News en la mayoria de devoluciones del controlador, por lo que habria que cambiar el "entry" por "news"

2022-09-19 14:01 UTC, gabodmc commented on routes/entries.js
> +router.post('/', validateCreate, post)
Aca deberia ser, por ejemplo: validationResults(schema)

2022-09-19 14:01 UTC, gabodmc commented on schemas/entries.js
> +    validateEntry(req, res, next)
Esto seria responsabilidad de la funcion reutilizable. Este archivo solo debe contener las validaciones

2022-09-19 16:03 UTC, Gabitandil commented on routes/entries.js
> +router.post('/', validateCreate, post)
tendria que pasarle el schema como un callback a la funcion  que tengo en middlewares?

2022-09-19 18:41 UTC, gabodmc requested changes
Mejoro un monton! Te dejo unas correcciones para realizar.

2022-09-19 18:41 UTC, gabodmc commented on middlewares/validateEntry.js
> +const validateEntry = (req, res, next) => {
Este archivo deberia llamarse validations.js ya que va a ser una funcion reutilizable y no solo para Entries.
Por otro lado, tiene que recibir un schema y poder evaluarlo. Como pista, buscar info sobre "check schema" de express-validator

2022-09-19 18:41 UTC, gabodmc commented on routes/entries.js
> +router.post('/', validationResultsSchema, validateEntry, post)
aca seria function(schema), no van por separado

2022-09-19 22:50 UTC, FrancoBaig requested changes

2022-09-19 22:50 UTC, FrancoBaig commented on controllers/entries.js
> +  post: catchAsync(async (req, res, next) => {
Gabi cuidado con esto, debes haber tenido algún problema al hacer merge con main, quitaste el controller "get" y agregaste el post

2022-09-19 22:55 UTC, FrancoBaig commented on schemas/entries.js
> +exports.validationResultsSchema = {
Esto me gusta, simplemente cambiaría el nombre del esquema a "entries" así no te queda "validationResultsSchema"

2022-09-19 22:56 UTC, Gabitandil commented on controllers/entries.js
> +  post: catchAsync(async (req, res, next) => {
es que yo cuando hice la branch vos todavia no habias creado la ruta get entonces quedo asi, fijate que en el primer commit no tengo una ruta get en el controller "news" (q despues renombre entries), pero eso no deberia reemplazar tu get porque despues lo agregaste y ya no aparecen conflictos con la rama main q tiene tu get mergeado, corregime si estoy equivocado pero creo que es por eso

2022-09-19 23:14 UTC, gabodmc commented on controllers/entries.js
> +        message: 'post test succesfull',
Esto es solo una correccion de typos:
'entry successfully created'

2022-09-19 23:14 UTC, gabodmc approved these changes
Bien esas correcciones. Quedo genial el PR!

2022-09-19 23:27 UTC, FrancoBaig approved these changes

2022-09-20 00:25 UTC, federicocapucci approved these changes

2022-09-20 00:27 UTC, merged