OT287-41 Created Model and Migration for News
alkemyTech/OT287-server pull request #3
Opened 2022-09-15 04:19 UTC by Gabitandil

## Jira Ticket

- [OT287-](OT287-41)

## Description
AS: usuario administrador
I Want: gestionar las Novedades
To: administrar el contenido

 Criterios de aceptación: Las entradas serán el contenido publicado en la sección "Novedades" del sitio. Nombre de tabla: entries. Campos: name, content, image, categoryId, type (una entrada podrá ser event, news, etc), deletedAt (utilizado para softDelete)

## Evidence:

![1 (OT287-41)](https://user-images.githubusercontent.com/70545509/190313057-b091ca5f-865f-47dd-9a79-7eafba174f69.png)

2022-09-15 04:31 UTC, guiniote requested changes
Gabi, fijate que te comenté algo en el código y además estás sumando 2 archivos al pull request que no tienen nada que ver con la tarjeta...eso no deberías subirlo (el borrado de .env.example y el index.js)

2022-09-15 04:31 UTC, guiniote commented on database/models/entry.js
> +      // define association here
Gabi, fijate que dice que tiene un categoryId...eso quiere decir que tu tabla va a estar relacionada con otra tabla de categorías. Esa relación la tenés que poner acá. Fijate cómo se relacionan tablas con sequelize (hay distintos tipos de relaciones...así que tenés que revisar en el proyecto cómo se tiene que relacionar con esta otra tabla)

2022-09-15 13:59 UTC, gabodmc requested changes
En lineas generales esta bien. Solo unos cambios en el codigo. Ademas, se subio un borrado de del archivo .env.example que no va. Tenes que volverlo a la misma version de main para que no lo marque.

2022-09-15 13:59 UTC, gabodmc commented on database/models/entry.js
> +    deletedAt: DataTypes.DATE
Este deletedAd aca no es necesario

2022-09-15 13:59 UTC, gabodmc commented on database/models/entry.js
> +    modelName: 'Entry',
Como la card esta pidiendo la posibilidad de softdeletes, hay que agregarle unas propiedades que permiten eso:
```
    paranoid: true,
    timestamps: true,
```

2022-09-15 13:59 UTC, gabodmc commented on services/index.js
> -    if (getIndex) {
Esta modificacion esta fuera del scope de la tarea

2022-09-15 19:12 UTC, guiniote commented
Gabi, fijate que sigue estando el .env.example en el PR

2022-09-15 19:22 UTC, gabodmc requested changes
Solo devolver al mismo estado que el main el archivo env.example, el resto esta perfecto

2022-09-15 19:36 UTC, federicocapucci approved these changes

2022-09-15 19:38 UTC, MrLuis-WebMaster approved these changes

2022-09-15 21:30 UTC, guiniote approved these changes

2022-09-16 11:49 UTC, gabodmc approved these changes

2022-09-16 15:39 UTC, merged