[ENDPOINT] OT287-100: DELETE /categories/:id
alkemyTech/OT287-server pull request #38
Opened 2022-09-20 21:58 UTC by federicocapucci

## Jira Ticket

- [OT287-1000](https://alkemy-labs.atlassian.net/browse/OT287-100)

## Description
AS: usuario administrador
I Want: eliminar una categoría existente
To: mantener la información actualizada

Criterios de aceptación:
DELETE /categories/:id - Deberá validar que la categoría existe y eliminarla, caso contrario devolver un error

## Evidence:

Pre-deletion
![image](https://user-images.githubusercontent.com/547180/191371932-6b3933be-c75a-4638-8b6a-a80e9ed47e8b.png)

After deletion
![image](https://user-images.githubusercontent.com/547180/191372033-7779ed3c-c1d3-4ea9-808f-764218ca0f67.png)

2022-09-20 22:04 UTC, Gabitandil approved these changes

2022-09-20 22:05 UTC, MrLuis-WebMaster approved these changes

2022-09-20 23:54 UTC, GregoHouse requested changes

2022-09-20 23:54 UTC, GregoHouse commented on services/categories.js
> +    const entry = await Category.destroy({ where: { id: categoryId } })
Fede, creo que llamaste la const como "entry" siendo ese nombre para el archivo de entries/news. Deberias llamar la const "category" para seguir misma logica y haga sentido con el archivo categories.

2022-09-20 23:54 UTC, GregoHouse commented on services/categories.js
> +    if (!entry) {
idem

2022-09-20 23:54 UTC, GregoHouse commented on services/categories.js
> +    return entry
idem

2022-09-21 02:51 UTC, gabodmc approved these changes

2022-09-21 12:35 UTC, GregoHouse approved these changes

2022-09-21 15:43 UTC, merged