[ENDPOINT] OT287-54: GET /users
alkemyTech/OT287-server pull request #40
Opened 2022-09-21 15:10 UTC by guiniote

## Jira Ticket

- [OT287-54](https://alkemy-labs.atlassian.net/browse/OT287-54)

## Description
AS: Usuario administrador
I Want: Visualizar un listado de Usuarios
To: Mantener un seguimiento de quiénes forman parte del sistema

Criterios de aceptación: GET a /users . Devolverá un listado de todos los Usuarios. Este endpoint solo deberá ser accesible por los Usuarios administradores.

## Evidence:
![image](https://user-images.githubusercontent.com/79290983/191541665-6dff2e1b-ba0d-478e-a087-e05bd6115fbd.png)

2022-09-21 15:22 UTC, ebereber approved these changes
Approve ger!

2022-09-21 16:06 UTC, gabodmc requested changes
Esta muy bien, pero estaria faltando que si sea accesible para usuarios administradores como lo indica la card. Hay una card asignada para este middleware, por lo que deben coordinar con la persona que la tiene

2022-09-21 16:45 UTC, guiniote commented
> Esta muy bien, pero estaria faltando que si sea accesible para usuarios administradores como lo indica la card. Hay una card asignada para este middleware, por lo que deben coordinar con la persona que la tiene

No lo hice para seguir la misma lógica de la tarjeta del sprint anterior, que me dijiste que banque que todavía no había nada de roles. Pero bueno, espero a que esté esa tarjeta...

2022-09-21 16:56 UTC, guiniote commented
Y supongo que te referís a la card de Eli, no? si es esa, por lo que entendí solo sería para usuario logueado, no para usuario admin como pide mi card...qué hago en ese caso? aplico solo logueo y en un futuro se aplicará rol?

2022-09-21 18:04 UTC, gabodmc commented
> > Esta muy bien, pero estaria faltando que si sea accesible para usuarios administradores como lo indica la card. Hay una card asignada para este middleware, por lo que deben coordinar con la persona que la tiene
> 
> No lo hice para seguir la misma lógica de la tarjeta del sprint anterior, que me dijiste que banque que todavía no había nada de roles. Pero bueno, espero a que esté esa tarjeta...

Claro, pero fijate que esta card puntualmente dice **"Este endpoint solo deberá ser accesible por los Usuarios administradores."**
Esto es lo que les comentaba anteriormente

2022-09-21 18:08 UTC, gabodmc commented
> Y supongo que te referís a la card de Eli, no? si es esa, por lo que entendí solo sería para usuario logueado, no para usuario admin como pide mi card...qué hago en ese caso? aplico solo logueo y en un futuro se aplicará rol?

No, la de Eli solo esta haciendo la tokenización con JWT. 
No se si alguien la tiene asignada, pero hay una card que hace referencia a la protección de rutas. Si nadie la tiene asignada, avisame y te la asigno a vos o a alguno del equipo que quiera hacerla.

2022-09-21 18:13 UTC, GregoHouse commented
Chicos tranqui es mi card la de validar roleId - ahora termino laburo y la hago asi no soy un cuello botella

2022-09-21 18:34 UTC, Gabitandil commented
igual para no esperar a que termine grego podrias insertar usuarios ficticios en la tabla por lo que estuve viendo users tiene el atributo role Id supongo que segun el role id que tenga es considerado un user admin o no, asi podrias corroborar que el codigo funciona correctamente y despues cuando grego suba la card tendrias q renombrar segun como estan los valores pero ya estaria la estructuda armada

2022-09-21 19:42 UTC, guiniote commented
Ahí ví que es la de Grego...no le presté atención por las tags que tiene. Mala mía. Espero a que esté lo suyo y agrego el middleware. Avisá si te puedo dar una mano en algo, @GregoHouse

2022-09-23 01:31 UTC, GregoHouse requested changes

2022-09-23 01:31 UTC, GregoHouse commented on services/users.js
> +exports.getUsers = async () => {
Ger, excelente este service funciona barbaro!! Yo lo tengo local y ya junte el middleware isAdmin y autentication middleware de Eli ;)

2022-09-23 01:31 UTC, GregoHouse commented on routes/index.js
> +router.use('/auth', userRouter)
Ger, no entiendo porque pusiste el router.use('/auth', userRouter). Entiendo que no hace falta hay que usar el /users y hacer un get.

2022-09-23 01:31 UTC, GregoHouse commented on routes/users.js
> +router.get('/', get)
Ger, aca debería ir el middleware de authentication de Eli y luego el mío de isAdmin. Si queres ponelo aunque no ande y luego yo arreglo los fix. Asi podemos cerrar las 3 cards.

2022-09-27 22:03 UTC, guiniote commented
Evidence of middlewares working on the route:

User admin
![image](https://user-images.githubusercontent.com/79290983/192644764-28d2f497-6115-49c4-af71-3389098b2633.png)

![image](https://user-images.githubusercontent.com/79290983/192644959-25b1b3c6-9514-4218-b0c7-13f4986d38e6.png)

Get users with valid token
![image](https://user-images.githubusercontent.com/79290983/192645114-e2d19fcd-23be-433d-be58-b9c03e03a5a3.png)

Disabled token
![image](https://user-images.githubusercontent.com/79290983/192645265-fab75493-d433-4f47-bd4d-30d0969dfd58.png)

Switch role in the same user
![image](https://user-images.githubusercontent.com/79290983/192645421-9317e96f-45e7-48b4-9541-c41da9f4a866.png)

![image](https://user-images.githubusercontent.com/79290983/192645508-b734a03e-5523-4088-995e-1a1c58443383.png)

Get users with a non admin token
![image](https://user-images.githubusercontent.com/79290983/192645650-8b06f6ce-dfc6-43b8-a0a4-4cf335aa9109.png)

2022-09-28 00:49 UTC, gabodmc approved these changes

2022-09-28 01:30 UTC, federicocapucci approved these changes

2022-09-28 12:11 UTC, GregoHouse approved these changes

2022-09-28 15:50 UTC, merged