[MIDDLEWARES] OT287-34-37-53-54: Middlewares fixes to GET/ users as ad
alkemyTech/OT287-server pull request #50
Opened 2022-09-26 15:56 UTC by GregoHouse

## Jira Ticket

- [OT287-34-37-53-54](https://alkemy-labs.atlassian.net/jira/software/c/projects/OT287/boards/381?modal=detail&selectedIssue=OT287-54)

## Description
AS:
I Want:
To:

## Evidence:

![evidencia 1](https://user-images.githubusercontent.com/96206226/192324068-380263e1-33ec-4e8f-93c6-db216f48502a.PNG)
![evidencia 2](https://user-images.githubusercontent.com/96206226/192324074-e21122f3-3770-4b18-9e59-ea695c5d025d.PNG)
![evidencia 3](https://user-images.githubusercontent.com/96206226/192324078-4fd0e0be-e835-4997-b7ad-83488cca7d60.PNG)
![evidencia 4](https://user-images.githubusercontent.com/96206226/192324082-b929c4b7-078e-4c6d-9171-d3ae092a7789.PNG)
![evidencia 5](https://user-images.githubusercontent.com/96206226/192324084-e5549d05-28f6-44ca-b3f7-19cd40b687f5.PNG)

2022-09-26 17:32 UTC, eli-beg commented on middlewares/JWT.js
> +exports.decodeToken = (req) => {
esta función decodeToken no seria como una función auxiliar para utilizar (por ejemplo en isAdmin) que recibe el token y lo decodifica para obtener la info del user? O recibe un request y luego hay que extraer el token para decodificarlo? @gabodmc

2022-09-26 17:32 UTC, eli-beg commented on middlewares/JWT.js
> +  const token = jwt.sign(user.toJSON(), SECRET)
en el servicio createUser crea el usuario con el objeto devuelto de la base de datos, no veo porque pasarlo a json

2022-09-26 18:46 UTC, gabodmc requested changes
Es un fix muy complejo y poco explicito en lo que se esta modificando. Recordar que los fix tienen que ser chicos y apuntar a un problema puntual.

2022-09-26 20:04 UTC, GregoHouse commented
> Es un fix muy complejo y poco explicito en lo que se esta modificando. Recordar que los fix tienen que ser chicos y apuntar a un problema puntual. Si quieren lo charlamos en la meet

Gabo, sin problema lo conversamos en la meet no veo complejo los cambios realizados los enumero para que lo veamos en la daily 18 hs:
1.  controller/users.jsx --> se cambio el nombre de la propiedad "getMe" para que no choque con el "get" de Ger PR pendiente
2. middleware/JWT.jsx --> se agrego "try" y "catch" con objectErrors para seguir mismo patrón codigo
3. middleware/isAdmin.jsx --> es mi tarjeta que fue aprobada antes de las anteriores por ende le hice cambios para que Ger pueda terminar bien su PR
4. routs --> se cambio el "get" por "getMe" tambien porque el PR pendiente de Ger ya usa "get"
5. service/user.jsx --> se agrego un getUserById para poder traer el roleId del user en session (aunque me estoy dando cuenta que del token se puede obtener si consultar al DB - por ende esto podemos eliminarlo)

2022-09-26 20:17 UTC, gabodmc commented
> > Es un fix muy complejo y poco explicito en lo que se esta modificando. Recordar que los fix tienen que ser chicos y apuntar a un problema puntual. Si quieren lo charlamos en la meet
> 
> Gabo, sin problema lo conversamos en la meet no veo complejo los cambios realizados los enumero para que lo veamos en la daily 18 hs:
> 
> 1. controller/users.jsx --> se cambio el nombre de la propiedad "getMe" para que no choque con el "get" de Ger PR pendiente
> 2. middleware/JWT.jsx --> se agrego "try" y "catch" con objectErrors para seguir mismo patrón codigo
> 3. middleware/isAdmin.jsx --> es mi tarjeta que fue aprobada antes de las anteriores por ende le hice cambios para que Ger pueda terminar bien su PR
> 4. routs --> se cambio el "get" por "getMe" tambien porque el PR pendiente de Ger ya usa "get"
> 5. service/user.jsx --> se agrego un getUserById para poder traer el roleId del user en session (aunque me estoy dando cuenta que del token se puede obtener si consultar al DB - por ende esto podemos eliminarlo)

Claro, no es complejo porque vos lo hiciste. Pero imaginate que si entra otro dev a ver tu pr, y no esta en tema, le va a ser dificil poder entender un cambio grande. Encima aumenta la posibilidad de aprobar algo que genere algun bug.
Yo no tengo drama en aprobarlo, pero tenganlo en cuenta para futuros fixes

2022-09-26 22:46 UTC, guiniote requested changes
Grego, ahí revisé a fondo todo el código. Hice varios comentarios. Chusmeá bien lo que te puse, si querés nos conectamos un rato en discord y lo charlamos, pero el fix así no se puede pasar porque hay varias cosas que no estarían bien.

2022-09-26 22:46 UTC, guiniote commented on controllers/users.js
> +  getMe: catchAsync(async (req, res, next) => {
Grego, no entiendo para qué tenés este getMe en el controller...estás llamando a una función del middleware nada más, no a un servicio que va a ver a la base de datos o que hace algo en particular...justamente por eso es un middleware, porque la lógica y uso está abstraída del controller y se llama desde el router como un middleware, no como un método del controller a donde se llega desde una ruta...va en el medio, no es el destino al que quiero llegar cuando entro en determinada ruta.

2022-09-26 22:46 UTC, guiniote commented on middlewares/JWT.js
> +  const token = jwt.sign(user.toJSON(), SECRET)
Estoy de acuerdo con Eli...es una redundancia este "toJSON()". Tené en cuenta que si para hacer tus pruebas necesitaste convertirlo a JSON, quizás no es lo que se aplica a lo que ya está desarrollado (y como todo eso ya fue desarrollado, no podemos hacer algo incongruente con lo que ya existe, por más que exceda el scope de la card).

2022-09-26 22:46 UTC, guiniote commented on middlewares/JWT.js
> +exports.decodeToken = (req) => {
Bueno, esto lo hablamos en la meet...ya dijimos que no aplica este cambio, que la función de decode solo tiene que decodificar.

2022-09-26 22:46 UTC, guiniote commented on middlewares/isAdmin.js
>  const { ErrorObject } = require('../helpers/error')
Para mí en tu middleware solo tendrías que decodificar el token llamando a la función del middleware de Eli de JWT y en base a lo decodificado ver si es admin o no...en el scope de tu tarjeta solo tenés que ver si el usuario es admin o no...así que tenés que asumir que te está llegando un usuario válido, liberándote de esa responsabilidad (y al isAdmin).
Yo en mi ruta soy responsable de poner la validación de token para constatar que el usuario sea real y válido, y luego llamar al isAdmin que solo me tiene que decir si es admin o no.

2022-09-26 22:46 UTC, guiniote commented on routes/auth.js
> +router.get('/me', getMe)
Esto va de la mano de lo que dije en la nota del controller...no tiene sentido un endpoint que solo decodifica un usuario con un middleware.

2022-09-26 22:48 UTC, GregoHouse commented
@gabodmc  @eli-beg  Gabo y Eli, listo hice un commit mas deje todo los codigos de la card como estaban.

Solo hice fix en isAdmin - OT287-53 (mi card) y en logIn agregue para que se genere toquen. El resto lo deje como estaba. Con esto debería poder Ger hacer su ruta endpoint con dos middleware

2022-09-26 23:14 UTC, eli-beg commented on services/users.js
> +    const tokenSession = generateToken(user.toJSON())
ojo aca, hay que mandarle el user sin el .toJSON()

2022-09-27 19:59 UTC, guiniote requested changes
Grego, te pasé por discord unos cambios que considero que habría que hacer al isAdmin. Luego de eso se podría pasar el fix.

2022-09-27 21:16 UTC, GregoHouse commented
> Grego, te pasé por discord unos cambios que considero que habría que hacer al isAdmin. Luego de eso se podría pasar el fix.

list Ger, acabo tirar ultimo commit

2022-09-27 21:42 UTC, guiniote approved these changes
Ahora sí, todo parece estar bien!

2022-09-27 21:46 UTC, federicocapucci approved these changes

2022-09-27 21:48 UTC, eli-beg approved these changes

2022-09-28 00:42 UTC, MrLuis-WebMaster approved these changes

2022-09-28 00:54 UTC, gabodmc approved these changes

2022-09-28 02:18 UTC, merged