[ENDPOINT] OT287-57 users/:id
alkemyTech/OT287-server pull request #56
Opened 2022-10-01 14:05 UTC by ebereber

## Jira Ticket

- [OT287-57](https://alkemy-labs.atlassian.net/browse/OT287-58?atlOrigin=eyJpIjoiNGM4MzcyODgyNWMzNGEwM2FlMjI3YTBkMGRhN2UxNmMiLCJwIjoiaiJ9)

## Description
AS: Usuario administrador
I Want: Actualizar un usuario
To:Mantener los datos de Usuarios del proyecto actualizados

## Evidence:
![userst](https://user-images.githubusercontent.com/85371377/193413198-fcf71e1d-5ce5-4cd1-be92-98224cdeb5f7.png)

![getUser](https://user-images.githubusercontent.com/85371377/193413207-46121006-cd49-48d1-b9af-6caa13accb43.png)

### Error

![getusererror](https://user-images.githubusercontent.com/85371377/193413222-065de67a-2e59-448b-8ded-cd93c34c9fe1.png)

2022-10-01 15:50 UTC, gabodmc requested changes
Solo una pequeña correccion

2022-10-01 15:50 UTC, gabodmc commented on routes/users.js
> +router.get('/:id', getById)
aca deberian pasarle el middleware de ownership o si es admin cosa de que valide si es el dueño del id o si es admin para dejarlo editar

2022-10-02 15:01 UTC, federicocapucci approved these changes

2022-10-02 16:13 UTC, guiniote commented on routes/users.js
> +router.get('/:id', getById)
Claro, ahora hay que prestarle atención al "as" de la tarjeta de jira. jajaja

2022-10-02 16:36 UTC, ebereber commented on routes/users.js
> +router.get('/:id', getById)
verdad! sí!

2022-10-02 16:38 UTC, ebereber commented
#### Añado evidencia: en caso de no ser admin

![evidenciadd](https://user-images.githubusercontent.com/85371377/193465563-29cd81ff-67df-47f8-8177-32ee9803007a.png)

2022-10-02 16:54 UTC, gabodmc approved these changes

2022-10-02 18:12 UTC, guiniote approved these changes

2022-10-02 21:39 UTC, merged