[OT287-79] BACK: Edit Organization model/migration  with SN urls, Add PUT endpoint for Organizations
alkemyTech/OT287-server pull request #58
Opened 2022-10-01 18:23 UTC by federicocapucci

This is a 2 PR Jira ticket for FRONT and BACK. This PR belongs to changes made on the back.

## Jira Ticket

- [OT287-79](https://alkemy-labs.atlassian.net/browse/OT287-79)

## Description
AS:
I Want:
To:

AS: usuario administrador
I Want: editar los campos de contacto a la Organización
To: mostrar la información de la mejor manera posible. 

Criterios de aceptación:
Crear una migración para agregar las urls de redes sociales a una Organización. Se deberán agregar url de Facebook, Linkedin e Instagram

## Evidence:

![2022-10-01_15-22-57](https://user-images.githubusercontent.com/547180/193423034-ed2538be-820f-4d9b-8f28-4f8ea2076461.gif)

2022-10-01 20:02 UTC, gabodmc approved these changes

2022-10-02 11:49 UTC, GregoHouse approved these changes

2022-10-02 12:21 UTC, GregoHouse requested changes

2022-10-02 12:21 UTC, GregoHouse commented on services/organizations.js
> +      fbUrl: organization.fbUrl,
Fede, esto esta fuera del scope de tu card. Fijate mi card OT287-80 me pide que agregue al endpoint GET/organizations/id/publico los siguientes datos campos redes sociales:
- facebook
- instagram
- linkedin

Y ningun tarjeta menciona que sumes el "aboutUsText" y el "email" capaz mas adelante hay otra tarjeta que pide agregarlas

2022-10-02 14:47 UTC, GregoHouse requested changes

2022-10-02 14:47 UTC, GregoHouse commented on services/organizations.js
> -      welcomeText: organization.welcomeText,
Fede, porque eliminaste este "welcomeText"??? Te consulto porque yo recuerdo que hay una card que ya fue aprobada que pedia que muestre ese campo. Y en otra card pide que el Home muestre el welcomeText

2022-10-02 14:58 UTC, GregoHouse approved these changes

2022-10-02 16:16 UTC, guiniote approved these changes

2022-10-02 17:27 UTC, merged