[OT287-76] Send welcome email
alkemyTech/OT287-server pull request #64
Opened 2022-10-03 23:07 UTC by Gabitandil

## Jira Ticket

- [OT287-](https://alkemy-labs.atlassian.net/browse/OT287-76)

## Description
AS: usuario 
I Want: recibir un correo cuando me contacto
To: confirmar que he completado el contacto con éxito.

Criterios de aceptación:
Cuando se registre un nuevo contacto en el sitio, enviar un email al usuario que completó el formulario agradeciendo su contacto. Para esto, utilizar el servicio de envío de emails.

## Evidence:

![evidencia1](https://user-images.githubusercontent.com/70545509/193701496-037b839b-44cc-40be-b7c6-cedf24224231.png)
![evidencia2](https://user-images.githubusercontent.com/70545509/193701499-38724e07-31e5-4692-b0da-780d9d7321d5.png)

2022-10-04 15:51 UTC, gabodmc requested changes
Solo un errror de typos.

2022-10-04 15:51 UTC, gabodmc commented on services/sendEmail.js
> +  RegisterWelcome: async (email, nombre) => {
registerWelcome

2022-10-04 16:29 UTC, guiniote reviewed
Che, pero la card dice que el mail se debe enviar al contactarse, no al registrarse.

2022-10-04 16:56 UTC, Gabitandil commented
> Che, pero la card dice que el mail se debe enviar al contactarse, no al registrarse.

Criterios de aceptación:
Cuando se registre un nuevo contacto en el sitio, enviar un email al usuario que completó el formulario agradeciendo su contacto. Para esto, utilizar el servicio de envío de emails.

dice que se envie cuando se registre, no hay otra forma de contacto,  lo otro seria entrar a las redes sociales de la ong pero para eso no se completa ningun formulario y dice que debo enviar un mail al usuario que completo el formulario

2022-10-04 17:39 UTC, guiniote commented
Que se registre un nuevo contacto...hay un formulario de contacto, por lo que estuve viendo en otros PRs

2022-10-04 19:46 UTC, federicocapucci commented
> Que se registre un nuevo contacto...hay un formulario de contacto, por lo que estuve viendo en otros PRs

Vos sabes que creo que tiene razon German, digamos que el wording podria haber sido mas claro, pero creo que es cuando alguien completa un 'contact us'  digamos, de echo, si lees el I want to:
"QUIERO recibir un correo cuando me **contacto**".

2022-10-04 19:46 UTC, federicocapucci requested changes
Entiendo que la tarjeta pide un email al momento de enviar un formulario de contacto/contact us.

2022-10-04 20:15 UTC, Gabitandil commented
> Entiendo que la tarjeta pide un email al momento de enviar un formulario de contacto/contact us.

ahi vi que hay 

> > Que se registre un nuevo contacto...hay un formulario de contacto, por lo que estuve viendo en otros PRs
> 
> Vos sabes que creo que tiene razon German, digamos que el wording podria haber sido mas claro, pero creo que es cuando alguien completa un 'contact us' digamos, de echo, si lees el I want to: "QUIERO recibir un correo cuando me **contacto**".

ahi mando un fix vi que es para el contact us

2022-10-04 20:40 UTC, gabodmc commented
> Che, pero la card dice que el mail se debe enviar al contactarse, no al registrarse.

Me

2022-10-04 20:41 UTC, gabodmc commented
> Che, pero la card dice que el mail se debe enviar al contactarse, no al registrarse.

Me sumo a esto. No me habia dado cuenta

2022-10-04 20:46 UTC, Gabitandil commented
> > Che, pero la card dice que el mail se debe enviar al contactarse, no al registrarse.
> 
> Me sumo a esto. No me habia dado cuenta

sii yo tampoco ahi mande el fix ahora deberia estar correcto

2022-10-04 21:10 UTC, gabodmc approved these changes

2022-10-04 21:50 UTC, federicocapucci approved these changes
dejo aprobado a condicion de lo q hablamos en slack :D

2022-10-04 21:53 UTC, federicocapucci commented
> 
Esta genial.
posiblemente toque cambiar el contenido del email cuando se agreguen campos al formulario de contacto, y si deseamos utilizarlo para parte de la demo.

2022-10-05 03:10 UTC, guiniote approved these changes

2022-10-05 11:22 UTC, FrancoBaig approved these changes

2022-10-05 14:12 UTC, merged