[OT287-84] Back: Add getById Testimonials Endpoint
alkemyTech/OT287-server pull request #67
Opened 2022-10-04 19:41 UTC by ebereber

## Jira Ticket
** **card perteneciente al front** 

- [OT287-84](https://alkemy-labs.atlassian.net/browse/OT287-84?atlOrigin=eyJpIjoiMzdhNmMyODZhY2FlNGM4NmE2NzRjN2RlMWYwOWFkNDAiLCJwIjoiaiJ9)

## Description
COMO: Usuario administrador
QUIERO: Crear o editar un testimonio existente
PARA: Mantener el contenido actualizado

## Evidence:

### Get by id

![backeviTesti](https://user-images.githubusercontent.com/85371377/193910246-9a8fe33f-5edc-4619-a588-7f2064016662.png)

### Error

![backeviTesti](https://user-images.githubusercontent.com/85371377/193910274-d68cc25c-1f74-4eca-9728-3983b1ff74a5.png)

2022-10-04 19:50 UTC, federicocapucci commented on services/testimonials.js
> +      throw new ErrorObject('No activity found', 404)
@FrancoBaig , editalo a 'testimonial' si podes.

2022-10-04 19:50 UTC, federicocapucci requested changes
Esta bien, solo te deje un comment a revisar :)

2022-10-04 22:08 UTC, ebereber commented on services/testimonials.js
> +      throw new ErrorObject('No activity found', 404)
Buen ojo fede!

2022-10-05 00:39 UTC, gabodmc approved these changes

2022-10-05 01:30 UTC, federicocapucci approved these changes

2022-10-05 03:11 UTC, guiniote approved these changes

2022-10-05 11:23 UTC, FrancoBaig approved these changes

2022-10-05 14:07 UTC, merged