Create model and migration for Categories
alkemyTech/OT287-server pull request #7
Opened 2022-09-15 13:14 UTC by ebereber

## Jira Ticket

- [OT287-42]()

## Description
AS: usuario administrador
I Want: gestionar las Categorías de las Novedades
To: categorizar de forma correcta las novedades

## Evidence:

![categories](https://user-images.githubusercontent.com/85371377/190411969-f4d34253-3a9d-4ea4-9286-dbb5371accc1.png)

2022-09-15 13:49 UTC, gabodmc requested changes
Muy buen PR. Te marque unos cambios menores.

2022-09-15 13:49 UTC, gabodmc commented on database/models/category.js
> +    deleteAt: DataTypes.DATE
este deleteAd no va aca

2022-09-15 13:49 UTC, gabodmc commented on database/migrations/20220915122858-create-category.js
> +      deleteAt: {
deletedAt

2022-09-15 15:01 UTC, guiniote reviewed
Eber, más allá de los comentarios de Gabo, fijate que en el PR pusiste el link del PR en sí y no de la tarjeta de Jira

2022-09-15 19:09 UTC, guiniote requested changes

2022-09-15 19:09 UTC, guiniote commented on database/migrations/20220915122858-create-category.js
> +      createdAt: {
Por lo que entendí, Gabo te había dicho que acá no saques el deletedAt (eso era en models), sino que le habías puesto "deleteAd". Faltaba una "d" antes del "At". Si es así, habría que volver a ponerlo acá 😛

2022-09-15 19:15 UTC, ebereber commented on database/migrations/20220915122858-create-category.js
> +      createdAt: {
ohh jisus. gracias!

2022-09-15 20:28 UTC, guiniote approved these changes

2022-09-16 11:44 UTC, gabodmc approved these changes
Buenas correcciones y buen PR!

2022-09-16 12:19 UTC, eli-beg approved these changes

2022-09-16 18:02 UTC, merged