[TEST] OT287-116: Test endpoint /Organizations
alkemyTech/OT287-server pull request #74
Opened 2022-10-07 22:36 UTC by GregoHouse

## Jira Ticket

- [OT287-116](https://alkemy-labs.atlassian.net/jira/software/c/projects/OT287/boards/381?modal=detail&selectedIssue=OT287-116)

## Description
COMO desarrollador
QUIERO disponer de tests de /ong
PARA asegurar la integridad y funcionamiento del proyecto

Criterios de aceptación:
Testear el escenario de respuesta correcta, y escenarios de error, como ids inexistentes, validaciones, permisos, etc. El archivo deberá crearse dentro de la carpeta /test, con el mismo nombre del endpoint. Se puede utilizar como base el test creado a modo de demostración.

## Evidence:
![testingEvidence](https://user-images.githubusercontent.com/96206226/194671727-d4b20c20-4f3f-496d-840e-7cffa797de5a.PNG)

2022-10-08 15:49 UTC, guiniote approved these changes

2022-10-09 17:14 UTC, FrancoBaig requested changes

2022-10-09 17:14 UTC, FrancoBaig commented on package.json
> +    "test": "mocha tests/org.test.js --exit",
Grego todo muy bien, fijate que acá estás cambiando el script  de test y no van a correr el resto, debería quedar como `"test": mocha ./test/*.js` o `"test": mocha ./test/*.js --exit`, Y también fijate que estamos usando la carpeta "test" y no "test**s**".

2022-10-09 17:14 UTC, FrancoBaig commented on tests/org.test.js
> +
Acá estaría bueno renombrar el archivo a "organizations.test.js"

2022-10-11 12:33 UTC, GregoHouse commented on package.json
> +    "test": "mocha tests/org.test.js --exit",
Fran, gracias! Si fue mala mia. Vi que todas las carpetas estan el plural. services, controllers, schemas, routes, helpers, etc. Pero lo dejo con "test" en singular.
listo cambiado. Ahí subí el commit.

2022-10-11 12:34 UTC, GregoHouse commented on tests/org.test.js
> +
Fran, listo renombrado. ;)

2022-10-11 14:39 UTC, gabodmc approved these changes

2022-10-11 14:52 UTC, FrancoBaig approved these changes

2022-10-11 18:04 UTC, merged