[OT 287-117] - Create test for News Endpoint
alkemyTech/OT287-server pull request #76
Opened 2022-10-08 20:45 UTC by eli-beg

## Jira Ticket

- [OT287- 117 ](https://alkemy-labs.atlassian.net/browse/OT287-117)

## Description
AS: desarrollador
I Want: disponer de tests de los endpoints de /news
To: asegurar la integridad y funcionamiento del proyecto

Criterios de aceptación:
Testear el escenario de respuesta correcta, y escenarios de error, como ids inexistentes, validaciones, permisos, etc. El archivo deberá crearse dentro de la carpeta /test, con el mismo nombre del endpoint. Se puede utilizar como base el test creado a modo de demostración.

## Evidence:

![test](https://user-images.githubusercontent.com/85040647/194727204-230b98cc-573e-4614-9878-888c37d5222c.png)

2022-10-09 17:38 UTC, FrancoBaig requested changes

2022-10-09 17:38 UTC, FrancoBaig commented on test/News.test.js
> +const url= 'http://localhost:3000';
Está muy bien Eli, fijate que acá creo que sería mejor alternativa importar `app` y cambiar los `chai.request(url)` a `chai.request(app)`, así evitamos problemas de conflicto con los puertos (por ejemplo, yo uso 3001 para el server y me fallarían tus tests)

2022-10-09 17:38 UTC, FrancoBaig commented on test/News.test.js
> +    it('should post a new with an existing categoryId', (done) => {
acá hay un error con el mensaje del it, ya que **no** debe agregar la novedad **si no** existe la categoría

2022-10-09 21:34 UTC, guiniote commented
Me acoplo a lo que dijo Fran

2022-10-11 13:11 UTC, eli-beg commented on test/News.test.js
> +const url= 'http://localhost:3000';
totalmente gracias por avisarme

2022-10-11 13:59 UTC, FrancoBaig approved these changes

2022-10-11 20:35 UTC, Gabitandil approved these changes

2022-10-11 20:37 UTC, merged