Created model and migration for Testimonial
alkemyTech/OT287-server pull request #8
Opened 2022-09-15 15:33 UTC by eli-beg

## Jira Ticket

- [OT287-82](https://alkemy-labs.atlassian.net/browse/OT287-82)

## Description

AS: usuario administrador
I Want: gestionar los Testimonios
To:  administrar el contenido

Criterios de aceptación:
Se podrán gestionar los Testimonios de personas sobre la ONG. Nombre de tabla: testimonials. Campos: name, image, content

## Evidence:

![OT287-82](https://user-images.githubusercontent.com/85040647/190445736-604d235e-d354-4a15-ac4f-7b0050ee1c9d.png)

2022-09-15 15:46 UTC, gabodmc requested changes
A nivel codigo nada que objetar. Solo unas correcciones dentro del PR, ya que se fueron del scope de la tarea asignada. 
Ademas del env y del package, tambien sacar de este pr la modifiacion del package-lock. Recordar de usar el source control para evitar subir archivos no relacionados al pr

2022-09-15 15:46 UTC, gabodmc commented on package.json
> +    "sequelize-cli": "^6.2.0",
Volver este cambio del package ya que esta fuera del scope de la tarea

2022-09-15 15:46 UTC, gabodmc commented on .env.example
> -DB_PORT=3306
No eliminar el archivo .env.example en el pr ya que esta fuera del scope de la tarea

2022-09-16 11:46 UTC, gabodmc requested changes
Todavia esta el archivo de package-lock modificado en el pr.

2022-09-16 12:46 UTC, FrancoBaig approved these changes

2022-09-16 13:38 UTC, gabodmc approved these changes
Buenas correcciones. Adentro este PR!

2022-09-16 14:19 UTC, guiniote approved these changes
Buenísimo Eli

2022-09-16 15:42 UTC, Gabitandil approved these changes

2022-09-16 15:45 UTC, merged